
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/widgets/Header/Header"
import Footer from "@/widgets/Footer/Footer"
import "./globals.css";
import '@/i18n'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('https://m.mashina.kg/bundles/client/default/img/banners/branding-mbankavtokredit-18aug2025.webp')",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-0">
          <Header />
        </div>
        <main className="max-w-7xl mx-auto bg-white/95 backdrop-blur px-4 sm:px-6 lg:px-10 min-h-screen  ">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


