import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; 
import {Header} from "@/widgets/Header/Header" 
import Footer from "@/widgets/Footer/Footer"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  px-0 sm:px-1 `}
      >
        <Header/>
        {children} 
        <Footer/>
      </body>
    </html>
  );
}
